-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 22:46:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `USER_NO` INT NULL AUTO_INCREMENT,
  `USER_EMAIL_ID` VARCHAR(50) NOT NULL,
  `USER_NAME` VARCHAR(30) NULL,
  `USER_PASSWORD` VARCHAR(80) NULL,
  `USER_COMPANY_NAME` VARCHAR(30) NULL,
  `USER_COMPANY_ADDRESS` VARCHAR(50) NULL,
  `USER_ACTIVE` TINYINT NULL,
  `USER_CREATE_TS` DATETIME NULL,
  `USER_UPDATE_TS` DATETIME NULL,
  PRIMARY KEY (`USER_NO`),
  UNIQUE INDEX `USER_EMAIL_ID_UNIQUE` (`USER_EMAIL_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`controller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`controller` (
  `CONTROLLER_ID` INT NOT NULL AUTO_INCREMENT,
  `CONTROLLER_USER_ID` INT NULL,
  `CONTROLLER_NUMBER` INT NULL,
  `CONTROLLER_NAME` VARCHAR(35) NULL,
  `CONTROLLER_CREATE_TS` DATETIME NULL,
  `CONTROLLER_UPDATE_TS` DATETIME NULL,
  PRIMARY KEY (`CONTROLLER_ID`),
  INDEX `controllerfk_idx` (`CONTROLLER_USER_ID` ASC),
  CONSTRAINT `controllerfk`
    FOREIGN KEY (`CONTROLLER_USER_ID`)
    REFERENCES `mydb`.`user` (`USER_NO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
